/**
 * Generates a static sitemap.xml for the WardCheck SPA by querying the
 * database directly for facility and blog post slugs. This app has no
 * SSR/server, so the sitemap can't be produced by a dynamic route — it's
 * regenerated by this script instead.
 *
 * Usage: pnpm --filter @workspace/wardcheck run generate-sitemap -- <site-origin>
 * Example: pnpm --filter @workspace/wardcheck run generate-sitemap -- https://wardcheck.example.com
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { db, hospitalsTable, blogPostsTable, pool } from "@workspace/db";

async function main() {
  const origin = process.argv.slice(2).find((arg) => arg !== "--");
  if (!origin) {
    console.error(
      "Usage: pnpm --filter @workspace/wardcheck run generate-sitemap -- <site-origin>\n" +
        "Example: pnpm --filter @workspace/wardcheck run generate-sitemap -- https://wardcheck.example.com",
    );
    process.exit(1);
  }
  const base = origin.replace(/\/$/, "");

  const hospitals = await db.select({ slug: hospitalsTable.slug, updatedAt: hospitalsTable.updatedAt }).from(hospitalsTable);
  const posts = await db.select({ slug: blogPostsTable.slug, updatedAt: blogPostsTable.updatedAt }).from(blogPostsTable);

  const staticUrls = ["/", "/search", "/report", "/blog", "/about", "/privacy", "/terms", "/contact"];

  const urlEntries: string[] = [];

  for (const path of staticUrls) {
    urlEntries.push(`  <url>\n    <loc>${base}${path}</loc>\n  </url>`);
  }
  for (const h of hospitals) {
    urlEntries.push(
      `  <url>\n    <loc>${base}/facility/${h.slug}</loc>\n    <lastmod>${h.updatedAt.toISOString().slice(0, 10)}</lastmod>\n  </url>`,
    );
  }
  for (const p of posts) {
    urlEntries.push(
      `  <url>\n    <loc>${base}/blog/${p.slug}</loc>\n    <lastmod>${p.updatedAt.toISOString().slice(0, 10)}</lastmod>\n  </url>`,
    );
  }

  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urlEntries.join("\n")}\n</urlset>\n`;

  const outPath = resolve(import.meta.dirname, "../public/sitemap.xml");
  writeFileSync(outPath, xml, "utf-8");

  console.log(`Wrote ${urlEntries.length} URLs to ${outPath}`);
  await pool.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
