CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE TYPE "AdminRole" AS ENUM ('SUPER_ADMIN', 'ADMIN');
CREATE TYPE "ReportStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE "WorkplaceConcern" AS ENUM (
  'DELAYED_SALARY',
  'SALARY_NOT_PAID',
  'UNDERPAYMENT',
  'CONTRACT_DISPUTE',
  'POOR_MANAGEMENT',
  'BULLYING',
  'LONG_WORKING_HOURS',
  'UNSAFE_WORKING_CONDITIONS',
  'OTHER'
);

CREATE TABLE "admins" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "password_hash" TEXT NOT NULL,
  "role" "AdminRole" NOT NULL DEFAULT 'ADMIN',
  "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "admins_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "facilities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "wardcheck_id" TEXT NOT NULL,
  "facility_name" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "registration_number" TEXT NOT NULL,
  "ownership" TEXT NOT NULL,
  "county" TEXT NOT NULL,
  "sub_county" TEXT NOT NULL,
  "ward" TEXT NOT NULL,
  "facility_level" TEXT NOT NULL,
  "facility_type" TEXT NOT NULL,
  "reports_received" INTEGER NOT NULL DEFAULT 0,
  "primary_concern" "WorkplaceConcern",
  "last_updated" TIMESTAMPTZ(3),
  "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "facilities_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "reports" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "facility_id" INTEGER NOT NULL,
  "job_category" TEXT NOT NULL,
  "employment_year" INTEGER NOT NULL,
  "primary_concern" "WorkplaceConcern" NOT NULL,
  "email" TEXT,
  "fingerprint_hash" TEXT NOT NULL,
  "ip_hash" TEXT NOT NULL,
  "user_agent" TEXT NOT NULL,
  "status" "ReportStatus" NOT NULL DEFAULT 'PENDING',
  "submitted_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "approved_at" TIMESTAMPTZ(3),
  "approved_by" INTEGER,
  CONSTRAINT "reports_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "audit_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "action" TEXT NOT NULL,
  "performed_by" INTEGER,
  "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "admins_email_key" ON "admins"("email");
CREATE UNIQUE INDEX "facilities_wardcheck_id_key" ON "facilities"("wardcheck_id");
CREATE UNIQUE INDEX "facilities_slug_key" ON "facilities"("slug");
CREATE UNIQUE INDEX "facilities_registration_number_key" ON "facilities"("registration_number");
CREATE INDEX "facilities_facility_name_idx" ON "facilities"("facility_name");
CREATE INDEX "facilities_county_idx" ON "facilities"("county");
CREATE INDEX "facilities_facility_name_trgm_idx" ON "facilities" USING GIN ("facility_name" gin_trgm_ops);
CREATE INDEX "facilities_registration_number_trgm_idx" ON "facilities" USING GIN ("registration_number" gin_trgm_ops);
CREATE INDEX "facilities_county_trgm_idx" ON "facilities" USING GIN ("county" gin_trgm_ops);
CREATE INDEX "facilities_slug_trgm_idx" ON "facilities" USING GIN ("slug" gin_trgm_ops);
CREATE INDEX "reports_status_idx" ON "reports"("status");
CREATE INDEX "reports_fingerprint_hash_idx" ON "reports"("fingerprint_hash");
CREATE INDEX "reports_facility_fingerprint_idx" ON "reports"("facility_id", "fingerprint_hash");
CREATE INDEX "reports_facility_email_idx" ON "reports"("facility_id", "email");
CREATE INDEX "reports_submitted_at_idx" ON "reports"("submitted_at");
CREATE INDEX "audit_logs_created_at_idx" ON "audit_logs"("created_at");

ALTER TABLE "reports"
  ADD CONSTRAINT "reports_facility_id_fkey"
  FOREIGN KEY ("facility_id") REFERENCES "facilities"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "reports"
  ADD CONSTRAINT "reports_approved_by_fkey"
  FOREIGN KEY ("approved_by") REFERENCES "admins"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "audit_logs"
  ADD CONSTRAINT "audit_logs_performed_by_fkey"
  FOREIGN KEY ("performed_by") REFERENCES "admins"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

