CREATE TYPE "ImportHistoryStatus" AS ENUM (
  'RUNNING',
  'COMPLETED',
  'COMPLETED_WITH_ERRORS',
  'FAILED'
);

CREATE TABLE "import_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "started_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "completed_at" TIMESTAMPTZ(3),
  "duration" INTEGER,
  "records_fetched" INTEGER NOT NULL DEFAULT 0,
  "imported" INTEGER NOT NULL DEFAULT 0,
  "updated" INTEGER NOT NULL DEFAULT 0,
  "duplicates" INTEGER NOT NULL DEFAULT 0,
  "skipped" INTEGER NOT NULL DEFAULT 0,
  "failed" INTEGER NOT NULL DEFAULT 0,
  "status" "ImportHistoryStatus" NOT NULL DEFAULT 'RUNNING',
  "error_message" TEXT,
  CONSTRAINT "import_history_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "import_history_started_at_idx" ON "import_history"("started_at");
CREATE INDEX "import_history_status_idx" ON "import_history"("status");
CREATE UNIQUE INDEX "import_history_single_running_idx" ON "import_history"("status")
  WHERE "status" = 'RUNNING';
